version: '3.8'
name: rec-mydomain-com
services:
  # MariaDB database (Back)
  db:
    image: mariadb:11.2.2
    restart: "unless-stopped"
    user: mysql:mysql
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      MARIADB_ROOT_PASSWORD: <root_password>
      MARIADB_DATABASE: <mydomain>
      MARIADB_USER: <mydomain_user>
      MARIADB_PASSWORD: <mydomain_db_password>
    volumes:
      - "/share/Container/mysql/rec.mydomain.com:/var/lib/mysql"
  # Wordpress + PHP (Middle)
  wp:
    depends_on:
      - db
    image: wordpress:6.4.2-php8.2-fpm
    restart: "unless-stopped"
    user: www-data:www-data
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: <mydomain>
      WORDPRESS_DB_USER: <mydomain_user>
      WORDPRESS_DB_PASSWORD: <mydomain_db_password>
    volumes:
      - "/share/Container/www-data/rec.mydomain.com:/var/www/html"
    dns: 8.8.8.8
  # NGinx (Front)
  nginx:
    depends_on:
      - wp
    image: nginxinc/nginx-unprivileged:1.25.3
    restart: "unless-stopped"
    user: www-data:www-data
    volumes:
      - "/share/Container/nginx/rec.mydomain.com/nginx.conf:/etc/nginx/nginx.conf"
      - "/share/Container/www-data/rec.mydomain.com:/var/www/html"
    ports:
      - "28080:8080"